adminconfigform.settings:
  type: config_object
  label: 'Timezone settings'
  mapping:
    country:
      type: string
      label: 'Contry short code.'
    city:
      type: string
      label: 'City name.'
    timezone:
      type: mapping
      label: 'Timezone List (integer) settings'
      mapping:
        allowed_values:
          type: sequence
          label: 'Allowed values list'
          sequence:
            type: mapping
            label: 'Allowed value with label'
            mapping:
              value:
                type: string
                label: 'Value'
              label:
                type: label
                label: 'Label'
